version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build