version: 2.1

orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
# install node
      - node/install
      - checkout
# setup aws-cli
      - aws-cli/setup
# run back-end jobs
# install dependencies of back-end
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
# build back-end
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
# Installing AWS-EB-CLI
      - run:
          name: Installing AWS EB
          command: |
            npm run backend:aws-eb
# deploy back-end
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
# run front-end jobs
# install dependencies of front-end
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
# build front-end
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
# deploy front-end
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy


